project:
  type: website

website:
  title: "Creativity in LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jaasminew
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


